### ISSUE TITLE
add validations for creating a match

### ISSUE THREAD

**Issue by vinport16** [mes258/seniorProject#5]
if the match exists already, just create a UserMatch that connects the user who submitted the match to the match
check match to make sure the preferences are honored

**Comment by vinport16** [comment]
I made a method on profile called "compatible" - this needs to be filled in more

**Comment by mes258** [comment]
Values:

Gender: 
0: Male
1: Female
2: Non-binary

Preferences: 
0: Male
1: Female
2: Everyone

**Comment by mes258** [comment]
Compatibility check function should work now.
