### ISSUE TITLE
Photos

### ISSUE THREAD

**Issue by vinport16** [mes258/seniorProject#7]
add photos to the database and have them show up in the UI

**Comment by gjbsaiia** [comment]
Building out infrastructure in AWS to support photos.

General Approach::

Rails Server hosted in EC2 instance.
S3 Storage Bucket with public facing URLs store pictures. 

When user uploads photo on profile page, we use the ruby AWS-SDK to upload their photo into our S3 bucket. This returns an object key. The key is stored in the DB alongside the user profile. This key can be used to generate the URL used to display the pictures in the html.

**Comment by gjbsaiia** [comment]
Have ruby aws_sdk working for picture upload and public display outside of application
